version: "3"
services:
  aj_bank_server:
    image: aj_bank_server:v0.0.3
    build:      
      context: ../
      args:
        AJ_BANK_FIREBASE_ADMINSDK_SERVICE_ACCOUNT: $AJ_BANK_FIREBASE_ADMINSDK_SERVICE_ACCOUNT
        AJ_BANK_FIREBASE_CONFIG: $AJ_BANK_FIREBASE_CONFIG
        AJ_BANK_USER_TEST_EMAIL_00: $AJ_BANK_USER_TEST_EMAIL_00
        AJ_BANK_USER_TEST_PSW_00: $AJ_BANK_USER_TEST_PSW_00
        AJ_BANK_WORKSPACE_HOST: $AJ_BANK_WORKSPACE_HOST
      dockerfile: ./docker/dockerfile
      # dockerfile: ./docker/test_dockerfile
